<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="143126" started-at="2018-03-18T18:32:28Z" finished-at="2018-03-18T18:34:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="143126" started-at="2018-03-18T18:32:28Z" finished-at="2018-03-18T18:34:51Z">
      <class name="TestCases.TestCase2">
        <test-method status="PASS" signature="Login()[pri:0, instance:TestCases.TestCase2@70dd7e15]" name="Login" is-config="true" duration-ms="76043" started-at="2018-03-19T00:02:28Z" finished-at="2018-03-19T00:03:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="Test()[pri:0, instance:TestCases.TestCase2@70dd7e15]" name="Test" duration-ms="65193" started-at="2018-03-19T00:03:44Z" finished-at="2018-03-19T00:04:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Booking did not get created successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Booking did not get created successfullyat org.testng.Assert.fail(Assert.java:96)at TestCases.TestCase2.Test(TestCase2.java:121)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="Close()[pri:0, instance:TestCases.TestCase2@70dd7e15]" name="Close" is-config="true" duration-ms="1835" started-at="2018-03-19T00:04:49Z" finished-at="2018-03-19T00:04:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- TestCases.TestCase2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
